#!/usr/bin/env python3
"""
run_test_exec.py — wrap a pytest invocation in a self-contained TestExec-NNN/ folder
(GTaskSheet-np7s).

Usage:
    python scripts/run_test_exec.py [-q "investigation question"] [pytest args...]

Creates test-results/TestExec-NNN/ containing:
  - runs/             per-step scn traces (scn/reporter.py, via SCN_RUN_DIR)
  - gas-logs/         archived GAS logs (tests/helpers/gas_log.py, via SCN_GAS_LOG_DIR)
  - allure-results/   raw Allure results (--alluredir)
  - allure-report/    generated HTML report (npx allure generate, best-effort)
  - junit/pytest.xml  JUnit results (--junitxml)
  - pytest-stdout.log captured pytest console output
  - README.md         deployed version, test package, investigation question,
                       pass/fail summary

Regenerates test-results/INDEX.md afterwards (every TestExec-NNN, newest first,
with its README + a link to its allure-report/index.html if generated).

Exit code is pytest's exit code.
"""
import argparse
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = REPO_ROOT / "test-results"


def _next_exec_dir() -> Path:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    existing = []
    for p in RESULTS_DIR.glob("TestExec-*"):
        m = re.match(r"TestExec-(\d+)$", p.name)
        if m:
            existing.append(int(m.group(1)))
    n = (max(existing) + 1) if existing else 1
    d = RESULTS_DIR / f"TestExec-{n:03d}"
    d.mkdir()
    return d


def _deployed_version() -> str:
    sys.path.insert(0, str(REPO_ROOT))
    from tests.helpers.version import read_expected_version
    try:
        return read_expected_version()
    except Exception as exc:
        return f"<unknown: {exc}>"


def _junit_summary(xml_path: Path, rc: int) -> str:
    if not xml_path.exists():
        return f"**FAIL** — no junit xml produced (pytest exit code {rc})"
    root = ET.parse(xml_path).getroot()
    suites = root.findall(".//testsuite") or [root]
    tests = failures = errors = skipped = 0
    time_s = 0.0
    for s in suites:
        tests += int(s.get("tests", 0))
        failures += int(s.get("failures", 0))
        errors += int(s.get("errors", 0))
        skipped += int(s.get("skipped", 0))
        time_s += float(s.get("time", 0.0))
    passed = tests - failures - errors - skipped
    if tests == 0 and rc != 0:
        return f"**FAIL** — 0 tests collected, pytest exit code {rc}"
    status = "PASS" if (failures == 0 and errors == 0) else "FAIL"
    return (
        f"**{status}** — {passed}/{tests} passed, {failures} failed, "
        f"{errors} errors, {skipped} skipped ({time_s:.1f}s)"
    )


def _regenerate_index() -> None:
    entries = sorted(RESULTS_DIR.glob("TestExec-*"), key=lambda p: p.name)
    lines = [
        "# Test Execution Index",
        "",
        "Regenerated by `scripts/run_test_exec.py` after every run — do not edit by hand.",
        "",
    ]
    for d in reversed(entries):  # newest first
        readme = d / "README.md"
        if not readme.exists():
            continue
        lines.append(f"## [{d.name}]({d.name}/README.md)")
        lines.append("")
        for line in readme.read_text().splitlines():
            if line.startswith("# "):
                continue
            lines.append(line)
        report = d / "allure-report" / "index.html"
        if report.exists():
            link = f"{d.name}/allure-report/index.html"
            lines.append(f"- **Report:** [{link}]({link})")
        lines.append("")
    (RESULTS_DIR / "INDEX.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run pytest inside a self-contained test-results/TestExec-NNN/ folder."
    )
    parser.add_argument(
        "-q", "--question", default="(none recorded)",
        help="Free-text description of what this run is investigating.",
    )
    args, pytest_args = parser.parse_known_args()

    exec_dir = _next_exec_dir()
    runs_dir = exec_dir / "runs"
    gas_log_dir = exec_dir / "gas-logs"
    allure_results = exec_dir / "allure-results"
    allure_report = exec_dir / "allure-report"
    junit_path = exec_dir / "junit" / "pytest.xml"
    stdout_path = exec_dir / "pytest-stdout.log"
    for d in (runs_dir, gas_log_dir, allure_results, junit_path.parent):
        d.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env["SCN_RUN_DIR"] = str(runs_dir)
    env["SCN_GAS_LOG_DIR"] = str(gas_log_dir)

    cmd = [
        sys.executable, "-m", "pytest",
        *pytest_args,
        f"--alluredir={allure_results}",
        f"--junitxml={junit_path}",
    ]
    print(f"[run_test_exec] {exec_dir.name}: {' '.join(cmd)}")
    with open(stdout_path, "w", encoding="utf-8") as out:
        proc = subprocess.Popen(
            cmd, cwd=REPO_ROOT, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
        )
        for line in proc.stdout:
            sys.stdout.write(line)
            out.write(line)
        proc.wait()
    rc = proc.returncode

    allure_ok = False
    try:
        gen = subprocess.run(
            ["npx", "allure", "generate", str(allure_results), "-o", str(allure_report), "--clean"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=180,
        )
        allure_ok = gen.returncode == 0
        if not allure_ok:
            (exec_dir / "allure-generate.log").write_text(gen.stdout + gen.stderr)
    except Exception as exc:
        (exec_dir / "allure-generate.log").write_text(str(exc))

    summary = _junit_summary(junit_path, rc)
    version = _deployed_version()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    readme = f"""# {exec_dir.name}

- **When:** {timestamp}
- **Deployed GAS version:** {version}
- **Test package:** `{' '.join(pytest_args) or 'tests/'}`
- **Investigation:** {args.question}
- **Result:** {summary}
- **Allure report:** {'allure-report/index.html' if allure_ok else '(not generated — see allure-generate.log)'}
- **Trace files:** `runs/`
- **GAS logs:** `gas-logs/`
- **pytest output:** `pytest-stdout.log`
"""
    (exec_dir / "README.md").write_text(readme)

    _regenerate_index()
    print(f"[run_test_exec] {exec_dir.name}: {summary}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
